# Dataset settings
dataset:
  name: "CityScapes"
  root: "/data/datasets/PytorchDatasets/CityScapes-pytorch"
  full_train_path: "/data/datasets/PytorchDatasets/CityScapes-pytorch/leftImg8bit/train/"

# Output settings
output:
  path: "/data/output/myworkspace/CityScapes/bw_calculation/"

# Usecase-Patchify settings
usecase_patchifier:
  calculate_bw: true
  patch_size: 256
  imp_patch_quality: 100
  other_patch_quality: 10

# Usecase JPEG settings
usecase_jpeg:
  calculate_bw: false
  jpeg_quality: 50

# Uncompressed image settings
uncompressed_image:
  calculate_bw: false

# LUT settings
lut_path: "patches_lut_patch_lut/attn_lut_from_local_pretrained_model/from_local_pretrained_on_50data_lb1_local_keepindx_0.1_patchsize_256_.pkl"

# Evaluation settings
bpp: false
msssim: false
psnr: false
